global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node-exporter"
    static_configs:
      - targets: ['192.168.50.71:9100']
        labels: {'host': 'node1'}
      - targets: ['192.168.50.72:9100']
        labels: {'host': 'node2'}
      - targets: ['192.168.50.73:9100']
        labels: {'host': 'node3'}
      - targets: ['192.168.50.74:9100']
        labels: {'host': 'node4'}
      - targets: ['192.168.50.75:9100']
        labels: {'host': 'node5'}

  - job_name: "ceph-mgr"
    static_configs:
      - targets: ['192.168.100.71:9283']
        labels: {'host': 'node1'}



